DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'javademo') THEN
      CREATE DATABASE javademo;
   END IF;
END
$$;

\c javademo;

ALTER DATABASE javademo OWNER TO postgres;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL DEFAULT '$2a$10$1234567890123456789012'
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    roles VARCHAR(255),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price VARCHAR(255) NOT NULL,
    user_id BIGINT,
    CONSTRAINT items_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT,
    CONSTRAINT orders_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_items (
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    PRIMARY KEY (order_id, item_id),
    CONSTRAINT order_items_order_fk FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT order_items_item_fk FOREIGN KEY (item_id) REFERENCES items(id)
);

INSERT INTO user_roles (user_id, roles)
SELECT id, 'ROLE_USER' FROM users
WHERE NOT EXISTS (
    SELECT 1 FROM user_roles ur WHERE ur.user_id = users.id
);